version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
